### ISSUE TITLE
Übersetzungen funktionieren nicht.

### ISSUE THREAD

**Issue by dev-nm** [dev-nm/WP-StudioLink-Integration#1]
Leider funktionieren die Übersetzungen nicht. Ich habe schon Poedit und Loco Translate versucht, leider ohne positives Ergebnis. 
Ich werde noch einmal sehen, ob ich das Problem lösen kann, aber wer einen Tipp hat, kann mir gerne helfen :)

**Comment by marxphil** [comment]
Hab die Lösung. Pull Request kommt demnächst.
