### ISSUE TITLE
Twitter Boxen Größe / benötigen Counter

### ISSUE THREAD

**Issue by marxphil** [dev-nm/WP-StudioLink-Integration#2]
Die Twitter-Boxen sollten ein Limit-Counter haben, damit die Tweets nicht >280 Zeichen sind. Dabei muss die individuelle Podcast-Namen-Länge berücksichtigt werden.

Im selben Atemzug sollten die Größen angepasst werden -> deutlich kleiner

**Comment by dev-nm** [comment]
Leider bietet das Titan Framework meines Wissens nach keine Möglichkeit für ein Zeichenlimit oder eine andere Größe. Ich werde mich wohl doch noch einmal nach einem anderen Framework umsehen müssen.

**Comment by marxphil** [comment]
Naja, oder schlichtweg es mit Bordmitteln machen. So viel anders ist bei Nutzung der WordPress-API die Syntax auch nicht. https://codex.wordpress.org/Settings_API

Man muss ja nicht alles zwingend mit Frameworks machen ;)

**Comment by dev-nm** [comment]
Ja, da hast du schon recht. Ich werde mal mit dem Programmieren von Settings ohne Framework beginnen. Das wird dann aber erst die nächsten Tage etwas. Heute hab ich da leider nicht genug Zet für
