### ISSUE TITLE
Titan Framework Übersetzung wird nicht geladen.

### ISSUE THREAD

**Issue by dev-nm** [dev-nm/WP-StudioLink-Integration#8]
Obwohl die Übersetzungen jetzt funktionieren sollte, lädt die Übersetzung des Titan Frameworks nicht.

**Comment by marxphil** [comment]
Hast du da ein konkretes Beispiel?

**Comment by dev-nm** [comment]
Ja, die Switches sollten in der Deutschen Übersetzung ja nicht Enabled/Disabled sondern eher soetwas wie Eingeschaltet/Ausgeschaltet o.ä. anzeigen.
Das liegt wohl daran, dass die Übersetzung nicht geladen wird. Warum weiß ich nicht genau, aber ich versuche das mal mit einem load_textdomain_mofile Filter zu beheben.
